// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsLves6WExKgz4w4wQmjK9HyAkmWBtHyA',
    appId: '1:996649523240:android:885c491f6f1eac2eec3d1d',
    messagingSenderId: '996649523240',
    projectId: 'jahnhalle-4742a',
    storageBucket: 'jahnhalle-4742a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALBXbTVinH7wH1yNV9l5957slkl7S73yI',
    appId: '1:996649523240:ios:e98d036f19cd9a7aec3d1d',
    messagingSenderId: '996649523240',
    projectId: 'jahnhalle-4742a',
    storageBucket: 'jahnhalle-4742a.appspot.com',
    androidClientId: '996649523240-t6e2tt7vpa2uekqtjptlgg4e32t1vbq0.apps.googleusercontent.com',
    iosClientId: '996649523240-061ptl4voh6b9u7lmrjqibu86u5h5sfs.apps.googleusercontent.com',
    iosBundleId: 'com.app.jahnhalleProvider',
  );
}
